[package]
name = "rusk-bundle"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
reqwest = { workspace = true }
zip = { workspace = true }
walkdir = { workspace = true }
dirs = { workspace = true }
rusk-manifest = { workspace = true }
rusk-ui = { workspace = true }
