//! rusk-proguard: R8/ProGuard integration for Rusk projects.
//!
//! A Rusk app's Java surface is small and machine-generated (the
//! NativeActivity shim plus whatever `[[bindings]]`/JNI glue
//! `rusk-jnigen` produced), but it still needs correct keep rules: R8
//! doesn't know that a `native` method or a class referenced only from
//! Rust via `FindClass`/`GetMethodID` is actually reachable, and will
//! happily strip or rename it, breaking the JNI bridge at runtime with
//! no compile-time warning. This crate generates the keep-rule file a
//! Rusk project actually needs from what `rusk-jnigen` already scanned,
//! instead of asking the developer to hand-write ProGuard rules for
//! glue code they didn't hand-write either.

use std::path::{Path, PathBuf};
use std::process::Command;

use rusk_jnigen::JniFunction;
use rusk_manifest::RuskManifest;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ProguardError {
    #[error("io error at {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("r8 jar not found at {0}; it ships inside Android build-tools — run `rusk build` once first so build-tools are provisioned")]
    R8NotFound(PathBuf),
    #[error("`java -jar r8.jar` exited with status {0}")]
    R8Failed(i32),
}

/// Generates the keep-rule text a Rusk project needs, covering:
/// - The NativeActivity shim class and its constructor (the Android
///   framework instantiates it via reflection from the manifest's
///   `android:name`, which R8 can't see).
/// - Every `native` method `rusk-jnigen` found, keeping both the method
///   signature (so R8 doesn't rename/strip it out from under the linked
///   Rust symbol) and the declaring class.
pub fn generate_keep_rules(manifest: &RuskManifest, jni_functions: &[JniFunction]) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by `rusk build`. Regenerated on every build from the\n");
    out.push_str("# project's Rusk.toml and its JNI exports — do not hand-edit; add project-\n");
    out.push_str("# specific rules in a separate file and reference it via [proguard] extra_rules.\n\n");

    out.push_str("# The Android framework instantiates the activity by reflection from\n");
    out.push_str("# AndroidManifest.xml, which R8's static reachability analysis can't see.\n");
    out.push_str("-keep class android.app.NativeActivity { *; }\n");

    let shim_class = format!("{}.RuskShimActivity", manifest.package.id);
    out.push_str(&format!("-keep class {shim_class} {{\n    public <init>();\n}}\n\n"));

    if !jni_functions.is_empty() {
        out.push_str("# Every native method rusk-jnigen found bound to a Rust extern \"C\"/\n");
        out.push_str("# \"system\" symbol. Stripping or renaming these breaks the JNI bridge at\n");
        out.push_str("# runtime (the Rust side's mangled symbol name is fixed at compile time\n");
        out.push_str("# and can't be told about a rename R8 makes on the Java side).\n");
        let mut classes: Vec<&str> = jni_functions.iter().map(|f| f.class_name.as_str()).collect();
        classes.sort();
        classes.dedup();
        for class in classes {
            out.push_str(&format!("-keepclassmembers class {class} {{\n    native <methods>;\n}}\n"));
        }
        out.push('\n');
    }

    out.push_str("# Standard attribute keeps R8 needs to avoid breaking reflection-based\n");
    out.push_str("# framework behavior even in apps with no explicit reflection of their own.\n");
    out.push_str("-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod\n");
    out.push_str("-keepattributes SourceFile,LineNumberTable\n");

    out
}

/// Writes the generated rules (plus any `[proguard] extra_rules` file
/// content appended verbatim) to `out_path`, returning the path so the
/// caller can pass it to `r8`/`d8 --min-api ... @rules`.
pub fn write_keep_rules(
    manifest: &RuskManifest,
    jni_functions: &[JniFunction],
    extra_rules_file: Option<&Path>,
    out_path: &Path,
) -> Result<PathBuf, ProguardError> {
    let mut text = generate_keep_rules(manifest, jni_functions);
    if let Some(extra) = extra_rules_file {
        if extra.is_file() {
            let extra_text = std::fs::read_to_string(extra).map_err(|source| ProguardError::Io {
                path: extra.to_path_buf(),
                source,
            })?;
            text.push_str("\n# --- project-specific rules from ");
            text.push_str(&extra.display().to_string());
            text.push_str(" ---\n");
            text.push_str(&extra_text);
        }
    }
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent).map_err(|source| ProguardError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    std::fs::write(out_path, &text).map_err(|source| ProguardError::Io {
        path: out_path.to_path_buf(),
        source,
    })?;
    Ok(out_path.to_path_buf())
}

/// Runs R8 in full-mode (shrink + obfuscate + optimize) over the
/// project's compiled `.class` files, producing a minified `classes.dex`
/// in place of the plain `d8`-only dex step `rusk-build` uses by
/// default. `r8_jar` is the `r8.jar` bundled inside the provisioned
/// Android build-tools directory.
pub fn run_r8(
    r8_jar: &Path,
    class_dir: &Path,
    android_jar: &Path,
    keep_rules_file: &Path,
    dep_jars: &[PathBuf],
    out_dex_dir: &Path,
) -> Result<(), ProguardError> {
    if !r8_jar.is_file() {
        return Err(ProguardError::R8NotFound(r8_jar.to_path_buf()));
    }
    std::fs::create_dir_all(out_dex_dir).map_err(|source| ProguardError::Io {
        path: out_dex_dir.to_path_buf(),
        source,
    })?;

    let step = rusk_ui::Step::start("Minifying Java glue with R8 (shrink + obfuscate)");

    let mut cmd = Command::new("java");
    cmd.arg("-jar").arg(r8_jar);
    cmd.arg("--release");
    cmd.arg("--output").arg(out_dex_dir);
    cmd.arg("--lib").arg(android_jar);
    cmd.arg("--pg-conf").arg(keep_rules_file);
    for jar in dep_jars {
        cmd.arg("--classpath").arg(jar);
    }
    // Collect .class files under class_dir; R8's CLI takes individual
    // paths (or a jar), not a directory, unlike d8.
    let class_files = collect_class_files(class_dir);
    for f in &class_files {
        cmd.arg(f);
    }

    let status = cmd.status().map_err(|source| ProguardError::Io {
        path: PathBuf::from("java"),
        source,
    })?;
    if !status.success() {
        step.fail("r8 exited with an error");
        return Err(ProguardError::R8Failed(status.code().unwrap_or(-1)));
    }
    step.ok();
    Ok(())
}

fn collect_class_files(dir: &Path) -> Vec<PathBuf> {
    walkdir::WalkDir::new(dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|ext| ext == "class").unwrap_or(false))
        .map(|e| e.path().to_path_buf())
        .collect()
}
