[package]
name = "rusk-ndk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
sha1 = "0.10"
zip = { workspace = true }
dirs = { workspace = true }
which = { workspace = true }
rusk-ui = { workspace = true }
