[package]
name = "rusk-sdkmgr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reqwest = { workspace = true }
quick-xml = { workspace = true }
sha1 = "0.10"
zip = { workspace = true }
dirs = { workspace = true }
thiserror = { workspace = true }
rusk-ui = { workspace = true }
