//! rusk-apk: drives the external Android build-tools (`aapt2`, `d8`,
//! `zipalign`, `apksigner`) to turn generated resources, compiled native
//! libraries and (optionally) Java classes into a signed, installable
//! APK. Rusk does not reimplement the binary XML / resources.arsc format
//! itself — that machinery is what `aapt2` exists for — but every input
//! handed to it is generated by `rusk-androidgen`, not copied from a
//! template.

use std::path::{Path, PathBuf};
use std::process::Command;
use thiserror::Error;

/// Paths to the four external build-tools binaries a build needs.
/// Deliberately not tied to any one "where did these come from" story —
/// `rusk-build` fills this in from either `ANDROID_HOME` or the
/// `rusk-sdkmgr`-managed install, whichever is available.
pub struct ToolPaths {
    pub aapt2: PathBuf,
    pub d8: PathBuf,
    pub zipalign: PathBuf,
    pub apksigner: PathBuf,
}

#[derive(Debug, Error)]
pub enum ApkError {
    #[error("io error at {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("could not locate android.jar for API level {0}; set ANDROID_HOME to a Android SDK with `platforms/android-{0}/android.jar` installed")]
    MissingPlatformJar(u32),
    #[error("{tool} exited with status {status}\n--- stderr ---\n{stderr}")]
    ToolFailed {
        tool: String,
        status: i32,
        stderr: String,
    },
    #[error("zip error: {0}")]
    Zip(#[from] zip::result::ZipError),
}

pub struct ApkBuildInputs<'a> {
    pub staging_dir: &'a Path,
    pub manifest_xml: &'a str,
    pub strings_xml: &'a str,
    /// (abi jni-dir name, path to compiled .so)
    pub native_libs: &'a [(String, PathBuf)],
    /// Optional (class dir with .class files) to be dexed alongside any
    /// Java dependency jars.
    pub java_class_dir: Option<&'a Path>,
    pub java_dep_jars: &'a [PathBuf],
    pub sdk_compile: u32,
    pub android_jar: &'a Path,
    pub out_apk_unsigned: &'a Path,
}

fn run(tool_name: &str, cmd: &mut Command) -> Result<(), ApkError> {
    let output = cmd.output().map_err(|source| ApkError::Io {
        path: PathBuf::from(tool_name),
        source,
    })?;
    if !output.status.success() {
        return Err(ApkError::ToolFailed {
            tool: tool_name.to_string(),
            status: output.status.code().unwrap_or(-1),
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        });
    }
    Ok(())
}

pub fn locate_android_jar(api: u32) -> Result<PathBuf, ApkError> {
    let sdk_root = std::env::var_os("ANDROID_HOME")
        .or_else(|| std::env::var_os("ANDROID_SDK_ROOT"))
        .map(PathBuf::from)
        .ok_or(ApkError::MissingPlatformJar(api))?;
    let jar = sdk_root
        .join("platforms")
        .join(format!("android-{api}"))
        .join("android.jar");
    if jar.is_file() {
        Ok(jar)
    } else {
        Err(ApkError::MissingPlatformJar(api))
    }
}

/// Runs the full resource-compile -> link -> add-native-libs -> dex ->
/// sign -> align pipeline and leaves a ready-to-install APK at
/// `out_signed_apk`.
pub fn build_apk(
    tools: &ToolPaths,
    inputs: ApkBuildInputs,
    keystore: &KeystoreConfig,
    out_signed_apk: &Path,
) -> Result<(), ApkError> {
    let res_dir = inputs.staging_dir.join("res/values");
    std::fs::create_dir_all(&res_dir).map_err(|source| ApkError::Io {
        path: res_dir.clone(),
        source,
    })?;
    write(&res_dir.join("strings.xml"), inputs.strings_xml)?;

    let manifest_path = inputs.staging_dir.join("AndroidManifest.xml");
    write(&manifest_path, inputs.manifest_xml)?;

    let step = rusk_ui::Step::start("Compiling resources (aapt2 compile)");
    let compiled_res = inputs.staging_dir.join("compiled_res.zip");
    let mut cmd = Command::new(&tools.aapt2);
    cmd.arg("compile")
        .arg("--dir")
        .arg(inputs.staging_dir.join("res"))
        .arg("-o")
        .arg(&compiled_res);
    if let Err(e) = run("aapt2 compile", &mut cmd) {
        step.fail(&e.to_string());
        return Err(e);
    }
    step.ok();

    let android_jar = inputs.android_jar;

    let step = rusk_ui::Step::start("Linking resources (aapt2 link)");
    let mut cmd = Command::new(&tools.aapt2);
    cmd.arg("link")
        .arg("-o")
        .arg(inputs.out_apk_unsigned)
        .arg("-I")
        .arg(android_jar)
        .arg("--manifest")
        .arg(&manifest_path)
        .arg("-R")
        .arg(&compiled_res)
        .arg("--auto-add-overlay");
    if let Err(e) = run("aapt2 link", &mut cmd) {
        step.fail(&e.to_string());
        return Err(e);
    }
    step.ok();

    let step = rusk_ui::Step::start(format!(
        "Embedding {} native {}",
        inputs.native_libs.len(),
        if inputs.native_libs.len() == 1 { "library" } else { "libraries" }
    ));
    if let Err(e) = embed_native_libs(inputs.out_apk_unsigned, inputs.native_libs) {
        step.fail(&e.to_string());
        return Err(e);
    }
    step.ok();

    if inputs.java_class_dir.is_some() || !inputs.java_dep_jars.is_empty() {
        let step = rusk_ui::Step::start("Dexing Java classes (d8)");
        let dex_dir = inputs.staging_dir.join("dex-out");
        std::fs::create_dir_all(&dex_dir).map_err(|source| ApkError::Io {
            path: dex_dir.clone(),
            source,
        })?;
        let mut cmd = Command::new(&tools.d8);
        cmd.arg("--output").arg(&dex_dir);
        cmd.arg("--min-api").arg(inputs.sdk_compile.to_string());
        if let Some(class_dir) = inputs.java_class_dir {
            for entry in walk_files(class_dir, "class") {
                cmd.arg(entry);
            }
        }
        for jar in inputs.java_dep_jars {
            cmd.arg("--classpath").arg(jar);
            cmd.arg(jar);
        }
        if let Err(e) = run("d8", &mut cmd) {
            step.fail(&e.to_string());
            return Err(e);
        }
        if let Err(e) = embed_file(
            inputs.out_apk_unsigned,
            &dex_dir.join("classes.dex"),
            "classes.dex",
        ) {
            step.fail(&e.to_string());
            return Err(e);
        }
        step.ok();
    }

    let aligned = inputs.staging_dir.join("aligned.apk");
    let step = rusk_ui::Step::start("Aligning APK (zipalign)");
    let mut cmd = Command::new(&tools.zipalign);
    cmd.arg("-f").arg("-p").arg("4").arg(inputs.out_apk_unsigned).arg(&aligned);
    if let Err(e) = run("zipalign", &mut cmd) {
        step.fail(&e.to_string());
        return Err(e);
    }
    step.ok();

    let step = rusk_ui::Step::start("Signing APK (apksigner)");
    let mut cmd = Command::new(&tools.apksigner);
    cmd.arg("sign")
        .arg("--ks")
        .arg(&keystore.path)
        .arg("--ks-key-alias")
        .arg(&keystore.alias)
        .arg("--ks-pass")
        .arg(format!("pass:{}", keystore.password))
        .arg("--out")
        .arg(out_signed_apk)
        .arg(&aligned);
    if let Err(e) = run("apksigner", &mut cmd) {
        step.fail(&e.to_string());
        return Err(e);
    }
    step.ok();

    Ok(())
}

pub struct KeystoreConfig {
    pub path: PathBuf,
    pub alias: String,
    pub password: String,
}

/// Generates (or reuses) a debug keystore at `~/.rusk/debug.keystore` via
/// the JDK's `keytool`, so `rusk build` works out of the box without the
/// developer setting up signing for local/dev installs.
pub fn ensure_debug_keystore() -> Result<KeystoreConfig, ApkError> {
    let base = dirs::home_dir().ok_or_else(|| ApkError::Io {
        path: PathBuf::from("~"),
        source: std::io::Error::new(std::io::ErrorKind::NotFound, "no home directory"),
    })?;
    let dir = base.join(".rusk");
    std::fs::create_dir_all(&dir).map_err(|source| ApkError::Io {
        path: dir.clone(),
        source,
    })?;
    let keystore = dir.join("debug.keystore");
    let alias = "ruskdebug".to_string();
    let password = "android".to_string();

    if !keystore.is_file() {
        let step = rusk_ui::Step::start("Generating debug signing key");
        let mut cmd = Command::new("keytool");
        cmd.arg("-genkeypair")
            .arg("-keystore")
            .arg(&keystore)
            .arg("-alias")
            .arg(&alias)
            .arg("-keyalg")
            .arg("RSA")
            .arg("-keysize")
            .arg("2048")
            .arg("-validity")
            .arg("10000")
            .arg("-storepass")
            .arg(&password)
            .arg("-keypass")
            .arg(&password)
            .arg("-dname")
            .arg("CN=Rusk Debug, OU=Rusk, O=Rusk, L=Unknown, ST=Unknown, C=US");
        if let Err(e) = run("keytool", &mut cmd) {
            step.fail(&e.to_string());
            return Err(e);
        }
        step.ok();
    }

    Ok(KeystoreConfig {
        path: keystore,
        alias,
        password,
    })
}

fn write(path: &Path, contents: &str) -> Result<(), ApkError> {
    std::fs::write(path, contents).map_err(|source| ApkError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn walk_files(dir: &Path, ext: &str) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&d) else { continue };
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().and_then(|e| e.to_str()) == Some(ext) {
                out.push(path);
            }
        }
    }
    out
}

fn embed_native_libs(apk: &Path, libs: &[(String, PathBuf)]) -> Result<(), ApkError> {
    let entries: Vec<(String, PathBuf)> = libs
        .iter()
        .map(|(abi, path)| {
            let name = path.file_name().unwrap().to_string_lossy().into_owned();
            (format!("lib/{abi}/{name}"), path.clone())
        })
        .collect();
    append_files_to_zip(apk, &entries)
}

fn embed_file(apk: &Path, file: &Path, entry_name: &str) -> Result<(), ApkError> {
    append_files_to_zip(apk, &[(entry_name.to_string(), file.to_path_buf())])
}

fn append_files_to_zip(apk: &Path, entries: &[(String, PathBuf)]) -> Result<(), ApkError> {
    let file = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(apk)
        .map_err(|source| ApkError::Io {
            path: apk.to_path_buf(),
            source,
        })?;
    let mut writer = zip::ZipWriter::new_append(file)?;
    let options = zip::write::FileOptions::default()
        .compression_method(zip::CompressionMethod::Stored);
    for (entry_name, path) in entries {
        let data = std::fs::read(path).map_err(|source| ApkError::Io {
            path: path.clone(),
            source,
        })?;
        writer.start_file(entry_name, options)?;
        use std::io::Write;
        writer
            .write_all(&data)
            .map_err(|source| ApkError::Io {
                path: path.clone(),
                source,
            })?;
    }
    writer.finish()?;
    Ok(())
}
