[package]
name = "rusk-javadeps"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reqwest = { workspace = true }
quick-xml = { workspace = true }
zip = { workspace = true }
thiserror = { workspace = true }
dirs = { workspace = true }
rusk-ui = { workspace = true }
